categorical_variables:
    - person_age
    - person_home_ownership
    - loan_intent
    - loan_grade
    - cb_person_default_on_file

continuous_variables:
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length

dropped_columns:
  - id

target_column: loan_status

catboost_params:
  iterations: 1500
  eval_metric: AUC
  use_best_model: True
  objective: Logloss

catboost_verbose: 100

train_file_path: /Volumes/mlops_students/netojoseaugusto/dev_mlops/train.csv
test_file_path: /Volumes/mlops_students/netojoseaugusto/dev_mlops/test.csv