categorical_variables:
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file

continuous_variables:
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length

dropped_columns:
  - id

target_column: loan_status

model_params:
  iterations: 1500
  eval_metric: AUC
  use_best_model: True
  objective: Logloss

model_params_simple:
  iterations: 1500

model_verbose: 100

train_file_path: /Volumes/mlops_students/netojoseaugusto/dev_mlops/train_week2.csv
test_file_path: /Volumes/mlops_students/netojoseaugusto/dev_mlops/test_week2.csv

train_uc_location: mlops_students.netojoseaugusto.train_set
test_uc_location: mlops_students.netojoseaugusto.test_set

verbose: True

random_state: 42

catalog_name: mlops_students
schema_name: netojoseaugusto
