name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install the dependencies
        run: uv sync

      - name: Run pre-commit checks
        run: |
          uv pip install pre-commit
          uv pip install pytest@8.3.3
          uv run pre-commit run --all-files
